<a href="https://colab.research.google.com/github/varun2388/basics_python/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3,4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(4,5,6,7)])

In [ ]:
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
b.shape

(2, 4)

In [ ]:
b.size

8

In [ ]:
a.sum()

10

In [ ]:
a.prod()

24

In [ ]:
a.min()

1

In [ ]:
a.max()

4

In [ ]:
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
b= b.reshape(4,2)

In [ ]:
print(b)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
b.shape

(4, 2)

In [ ]:
 b[0,1]

2

In [ ]:
b[1,1]

4

In [ ]:
b[0,0]

1

In [ ]:
c= np.array([(1,2,3,4),(4,5,6,7)])
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
c.sum(axis=0)

array([ 5,  7,  9, 11])

In [ ]:
c.sum(axis=1)

array([10, 22])

In [ ]:
import pandas as pd
df=pd.DataFrame({'col1':['A','B','B','A'],'col2':[1,2,2,3]})

In [ ]:
df

col1  col2
0    A     1
1    B     2
2    B     2
3    A     3

In [ ]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
df[df.duplicated()]

col1  col2
2    B     2

In [ ]:
df1 = df.drop_duplicates()

In [ ]:
df1

col1  col2
0    A     1
1    B     2
3    A     3

In [ ]:
df2=df1.reset_index()

In [ ]:
df2

index col1  col2
0      0    A     1
1      1    B     2
2      3    A     3

In [ ]:
df3=df2.drop('index',axis=1)

In [ ]:
df3

col1  col2
0    A     1
1    B     2
2    A     3